version: '3'
services:
  web:
    container_name: minha-app-web
    build:
      context: ./
    volumes:
      - ./app:/var/www/html
      - ./app/uploads:/var/www/html/uploads
    ports:
      #- "80:80" #descomente esta linha se não tem proxy reverso
      - "8011:80" # mapeamento de porta para o proxy reverso.
